spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://gljmysql.server.com:3306/product}?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: ${DB_USER_NAME:root}
    password: ${DB_PWD:840416}
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/page/,classpath:/temp/,classpath:/temp2/
server:
  port: 8888

#MyBatis显示SQL
logging:
  level:
    com.mashibing.arica.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.glj.million.level.product.entity


nginx:
  html:
    roots: ${NGINX_HTML_ROOTS:/Users/gongliangjun/workspace_msb/product/src/main/resources/temp/},${NGINX_HTML2_ROOT:/Users/gongliangjun/workspace_msb/product/src/main/resources/temp2/}




jfinal:
  templates:
    location: ${JFINAL_TEMPLATES_LOCATION:/Users/gongliangjun/workspace_msb/product/src/main/resources/templates/}



# 启动命令  java -DDB_URL=jdbc:mysql://106.13.203.37:3306/product -DDB_USER_NAME=root -DDB_PWD=840416 -DNGINX_HTML_ROOT=/usr/local/openresty/nginx/html -DJFINAL_TEMPLATES_LOCATION=/root/glj/templates